AWSTemplateFormatVersion: '2010-09-09'
Description: 'trip-api
  Rest API para gerencias viagens
  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateTripRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn
  GetTripRecordsByPeriodFunction:
    Description: GetTripRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByPeriodFunction
      - Arn
Resources:
  CreateTripRecordFunction:
    Properties:
      CodeUri: s3://aws-sam-trip-fiap-deployt/70df4671084045718122c5cfc51eb7f0
      Events:
        CreateTripRecord:
          Properties:
            Method: post
            Path: /trips
          Type: Api
      Handler: br.com.fiap.handler.CreateTripRecord::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripRecordsByPeriodFunction:
    Properties:
      CodeUri: s3://aws-sam-trip-fiap-deployt/70df4671084045718122c5cfc51eb7f0
      Events:
        GetTripRecordsByPeriod:
          Properties:
            Method: get
            Path: /trips
            RequestParameters:
            - method.request.querystring.start
            - method.request.querystring.end
          Type: Api
      Handler: br.com.fiap.handler.GetTripRecordsByPeriod::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31