AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    trip-api
    Rest API para gerencias viagens
Globals:
    Function:
        Timeout: 50
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-aws-serveless-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.handler.CreateTripRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trips
           Method: post
  GetTripRecordByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-aws-serveless-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.handler.GetTripRecordById::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripRecordById:
         Type: Api
         Properties:
           Path: /trips/{id}
           Method: get         
  GetTripRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-aws-serveless-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.handler.GetTripRecordsByPeriod::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripRecordsByPeriod:
         Type: Api
         Properties:
           Path: /trips
           Method: get
           RequestParameters:
              - method.request.querystring.start
              - method.request.querystring.end
              
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: trip
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: S          
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes: 
        - IndexName: DateIndex
          KeySchema: 
            - AttributeName: date
              KeyType: HASH
          Projection:
             ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
Outputs:
    TripsAPI:
      Description: "Url do API Gateway para as funções"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/trips/"

    CreateTripRecordFunction:
      Description: "CreateTripRecord Lambda Function ARN"
      Value: !GetAtt CreateTripRecordFunction.Arn
      
    GetTripRecordsByPeriodFunction:
      Description: "GetTripRecordsByPeriod Lambda Function ARN"
      Value: !GetAtt GetTripRecordsByPeriodFunction.Arn

    GetTripRecordByIdFunction:
      Description: "GetTripRecordById Lambda Function ARN"
      Value: !GetAtt GetTripRecordByIdFunction.Arn