package br.com.fiap.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.S3Link;

import br.com.fiap.dto.TripDTO;

@DynamoDBTable(tableName = "trip")
public class Trip  implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private String id;

	private String date;

	private String country;

	private String city;

	private S3Link url;

	public Trip() { }
	public Trip(TripDTO trip) {
		this.city = trip.getCity();
		this.country = trip.getCountry();
		this.date = trip.getDate();
	 }

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBIndexHashKey(attributeName = "Date", globalSecondaryIndexName = "DateIndex")
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@DynamoDBAttribute(attributeName = "Country")
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return city;
	}

	@DynamoDBAttribute(attributeName = "City")
	public void setCity(String city) {
		this.city = city;
	}

	@DynamoDBAttribute(attributeName = "UrlS3")
	public S3Link getUrl() {
		return url;
	}

	public void setUrl(S3Link url) {
		this.url = url;
	}
 }
