package br.com.fiap.trips.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "trip")
public class TripEntity  implements Serializable {
    
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private String id;
    private String country;
    private String city;
    private String url;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id  = id; }

    @DynamoDBAttribute(attributeName = "Country")
    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }

    @DynamoDBAttribute(attributeName = "City")
    public String getCity() { return city; }
    public void setCity(String city) { this.city = city; }

    @DynamoDBAttribute(attributeName = "Url")
    public String getUrl() { return url; }
    public void setUrl(String url) { this.url = url; }
}